name: build
on: [push]

jobs:
  Debug_Build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker build
      run: docker build . --build-arg defs=DEBUG
  
  Production_Build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker build
      run: docker build . --build-arg defs=PROD
